### ISSUE TITLE
Can't change game icon 

### ISSUE THREAD

**Issue by speck1234** [Roet-Ivar/Webman-Classics-Maker#53]
DEBUG image content:C:/Users/jorda/Pictures/GHWT.png
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1892, in __call__
  File "webman-classics-maker.py", line 484, in <lambda>
    self.selection_system_list = GlobalVar.platform_paths
  File "webman-classics-maker.py", line 964, in image_replace_browser
    "#ffffff",
  File "webman-classics-maker.py", line 738, in __draw_pkg_images_on_canvas__
    text,
AttributeError: 'NoneType' object has no attribute 'lower'

**Comment by nuts4butts** [comment]
you have to rename the image to PIC1

**Comment by nuts4butts** [comment]
you need to rename the image to either PIC0, PIC1 or ICON1 depending on what you want to change, if you're trying to change the game icon name it ICON1, if you're trying to change the background image name it PIC1 and if you want to change the foreground image name it PIC0

**Comment by Roet-Ivar** [comment]
> you need to rename the image to either PIC0, PIC1 or ICON1 depending on what you want to change, if you're trying to change the game icon name it ICON1, if you're trying to change the background image name it PIC1 and if you want to change the foreground image name it PIC0

Appreciate your reply and the hilarious user name! Ever since my CECHA01 broke down on me I haven't had the ability to develop for this tool anymore.
Does my tool still work for later versions of webman?

**Comment by outlandernwah** [comment]
> > you need to rename the image to either PIC0, PIC1 or ICON1 depending on what you want to change, if you're trying to change the game icon name it ICON1, if you're trying to change the background image name it PIC1 and if you want to change the foreground image name it PIC0
> 
> Appreciate your reply and the hilarious user name! Ever since my CECHA01 broke down on me I haven't had the ability to develop for this tool anymore. Does my tool still work for later versions of webman?

Hi. Appreciate all the work you put into this. 

Yep, still works-ish. Couple of flake-y problems here and there but it gets the job done. 🎃

Happy spookers

Edit* forgot to mention, I'm on 4.92 (the latest & Evilnat 4.92.2)
